/**
 * `confirm()` tool — destructive-command gate w/ phone-side approval.
 *
 * Per plan §"v4.2 confirm() semantics" (2026-05-02):
 *   - shortId is a 4-char base32 (generated by PendingConfirmsRegistry).
 *   - Per-task cap: max 3 pending confirms; the 4th attempt is rejected
 *     immediately with reason 'task_blocked_confirm_cap', and the tool
 *     emits a tell() "blocked, stopping".  The DAEMON owns the auto-cancel
 *     of the task — this tool only signals the cap event.
 *   - Late reply (after expiresAt): reason='timeout', approved=false.
 *   - All confirm requests fan out to ALL sinks (terminal AND WhatsApp), so
 *     Sergio can ack from whichever surface is in front of him.
 *
 * The PendingConfirmsRegistry interface here is a STRUCTURAL stub of what
 * IMPL-7 will own at `src/tools/pending-confirms.ts`.  We don't import from
 * there because IMPL-7 ships in the same wave; both files compile in
 * isolation against this contract.
 */

import {
  type ChannelEvent,
  type DefinedTool,
  type Sink,
  type SinkBag,
  fanOut,
} from "./types.js";

// ---------------------------------------------------------------------------
// Public — registry contract that IMPL-7 will satisfy
// ---------------------------------------------------------------------------

export interface PendingConfirmCreateOptions {
  taskId: string;
  question: string;
  rationale: string;
  risk: string;
  /** Where the confirm originated.  Tells the registry which sink to default
   *  the user-prompt to if multiple are configured. */
  channel: "terminal" | "whatsapp" | "telegram" | "system";
  /** Override default 30-min ttl. */
  ttlMs?: number;
}

export interface PendingConfirmHandle {
  shortId: string;
  expiresAt: number;
  /** Resolves when the user answers OR ttl expires.  Resolution shape: */
  promise: Promise<PendingConfirmResolution>;
}

export type PendingConfirmResolution =
  | { decision: "yes" }
  | { decision: "no" }
  | { decision: "timeout" };

/**
 * IMPL-7's pending-confirms registry.  We declare only the surface
 * confirm.ts uses.  IMPL-7 may add more (e.g. iteration, late-reply handling
 * for the slash-command parser).
 */
export interface PendingConfirmsRegistry {
  /** Per-task max pending confirms.  Plan §"v4.2 confirm() semantics" = 3. */
  readonly maxPerTask: number;
  /** Number of CURRENTLY-OPEN confirms attributed to a given taskId. */
  countForTask(taskId: string): number;
  /**
   * Register a new pending confirm and return its shortId + a promise that
   * resolves when the user answers (or ttl expires).  IMPL-7 owns shortId
   * generation and ttl-timer lifecycle.
   *
   * MUST throw if `countForTask(taskId) >= maxPerTask`.  confirm.ts checks
   * the count first to give a structured error to the agent, but a race
   * between two tool calls still needs a server-side guard.
   */
  create(opts: PendingConfirmCreateOptions): PendingConfirmHandle;
}

// ---------------------------------------------------------------------------
// Public — defineConfirmTool options
// ---------------------------------------------------------------------------

/** Confirm-specific sink bag.  See `TellSinks` for the SinkBag-compat note. */
export type ConfirmSinks = SinkBag & {
  terminal?: Sink;
  whatsapp?: Sink;
  telegram?: Sink;
};

export interface DefineConfirmToolOptions {
  pendingConfirms: PendingConfirmsRegistry;
  sinks: ConfirmSinks;
  /**
   * Returns the currently-active task id, or null if no task is running.
   * Confirm without a running task is a programming error and returns
   * approved=false reason='no_active_task'.
   */
  getCurrentTaskId: () => string | null;
  /**
   * Optional Sink hook for emitting the "blocked, stopping" tell when the
   * per-task confirm cap is hit.  Defaults to broadcasting a synthetic
   * tell-style event through `sinks` (urgency=blocked).
   */
  emitCapHitTell?: (taskId: string) => Promise<void>;
  /** Override for time source — primarily for tests. */
  now?: () => number;
  /**
   * Optional sanitizer applied to `action` / `rationale` / `risk` BEFORE
   * the confirm-request event is fanned out.  Production wires this to
   * `redactCredentialShapes` (RS-4 mitigation per plan §"Pitfall RS-4").
   * When omitted, fields are sent as-is — tests do this to keep their
   * assertions on raw input.
   */
  sanitizeOutbound?: (text: string) => string;
}

// ---------------------------------------------------------------------------
// Public — confirm tool result shape
// ---------------------------------------------------------------------------

export type ConfirmResult =
  | {
      approved: true;
      shortId: string;
      reason: "user_yes";
    }
  | {
      approved: false;
      shortId: string | null;
      reason:
        | "user_no"
        | "timeout"
        | "task_blocked_confirm_cap"
        | "no_active_task";
    };

// ---------------------------------------------------------------------------
// Public — factory
// ---------------------------------------------------------------------------

export function defineConfirmTool(opts: DefineConfirmToolOptions): DefinedTool {
  const now = opts.now ?? Date.now;

  return {
    name: "confirm",
    description: [
      "Request explicit yes/no approval from the user before proceeding.",
      "",
      "The destructive-command guard FORCES this tool when the agent attempts",
      "irreversible operations (rm -rf, git push --force, DROP DATABASE,",
      "credential file modification, OS-level changes, cloud resource deletion).",
      "",
      "Provide:",
      "  - action: WHAT you want to do (one sentence)",
      "  - rationale: WHY it is necessary",
      "  - risk: WHAT is irreversible if approved",
      "",
      "Times out after 30 minutes — defaults to NOT approved.  Per task you",
      "can have at most 3 pending confirms; the 4th will block the task.",
    ].join("\n"),
    parameters: {
      type: "object",
      required: ["action", "rationale", "risk"],
      properties: {
        action: {
          type: "string",
          description: "What you want to do (one sentence).",
        },
        rationale: {
          type: "string",
          description: "Why this is necessary.",
        },
        risk: {
          type: "string",
          description: "What is irreversible if approved.",
        },
      },
    },
    async execute(args): Promise<ConfirmResult> {
      const sanitize = opts.sanitizeOutbound ?? ((s: string) => s);
      // RS-4: sanitize agent-controlled prose BEFORE it is registered into
      // the pending-confirms registry OR fanned out to sinks.  This catches
      // the case where the agent accidentally pastes a secret into one of
      // the prompt fields.
      const action = sanitize(String(args.action ?? "").trim());
      const rationale = sanitize(String(args.rationale ?? "").trim());
      const risk = sanitize(String(args.risk ?? "").trim());

      const taskId = opts.getCurrentTaskId();
      if (!taskId) {
        return {
          approved: false,
          shortId: null,
          reason: "no_active_task",
        };
      }

      // ---- Per-task cap pre-check (cheap; race-safe via registry guard) ----
      if (opts.pendingConfirms.countForTask(taskId) >= opts.pendingConfirms.maxPerTask) {
        // Emit the "blocked, stopping" tell.  The DAEMON sees this and
        // auto-cancels the task — this tool just signals it.
        const emit = opts.emitCapHitTell ?? defaultEmitCapHitTell(opts.sinks, now);
        try {
          await emit(taskId);
        } catch {
          // Tell delivery is best-effort; do not let it mask the structured
          // error we return to the agent.
        }
        return {
          approved: false,
          shortId: null,
          reason: "task_blocked_confirm_cap",
        };
      }

      // ---- Register the pending confirm ----
      let handle: PendingConfirmHandle;
      try {
        handle = opts.pendingConfirms.create({
          taskId,
          question: action,
          rationale,
          risk,
          channel: "system",
        });
      } catch (e) {
        // Race: registry-side guard tripped (count went over between our
        // pre-check and the create).  Emit the same blocked-tell signal.
        const emit = opts.emitCapHitTell ?? defaultEmitCapHitTell(opts.sinks, now);
        try {
          await emit(taskId);
        } catch {
          /* ignore */
        }
        return {
          approved: false,
          shortId: null,
          reason: "task_blocked_confirm_cap",
        };
      }

      // ---- Fan out the confirm_request event to every configured sink ----
      const event: ChannelEvent = {
        type: "confirm_request",
        shortId: handle.shortId,
        question: action,
        rationale,
        risk,
        expiresAt: handle.expiresAt,
        ts: now(),
      };
      // Best-effort send; even if all sinks fail the registry's promise will
      // still be resolvable via the slash-command parser path (e.g. CLI),
      // so we do NOT short-circuit here.
      await fanOut(opts.sinks, event);

      // ---- Await the user's decision (or timeout) ----
      const resolution = await handle.promise;
      switch (resolution.decision) {
        case "yes":
          return {
            approved: true,
            shortId: handle.shortId,
            reason: "user_yes",
          };
        case "no":
          return {
            approved: false,
            shortId: handle.shortId,
            reason: "user_no",
          };
        case "timeout":
          return {
            approved: false,
            shortId: handle.shortId,
            reason: "timeout",
          };
      }
    },
  };
}

// ---------------------------------------------------------------------------
// Internal — default cap-hit tell
// ---------------------------------------------------------------------------

function defaultEmitCapHitTell(
  sinks: ConfirmSinks,
  now: () => number,
): (taskId: string) => Promise<void> {
  return async (taskId: string) => {
    const event: ChannelEvent = {
      type: "tell",
      urgency: "blocked",
      text: `pi: blocked — confirm cap hit (3 declined or pending) for task ${taskId}, stopping.`,
      ts: now(),
    };
    await fanOut(sinks, event);
  };
}
